apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rosaassignment  # Corrected namespace name
  name: rosa-assignment-role
rules:
  - apiGroups: [""]
    resources: ["services", "secrets"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
