apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-route
spec:
  host: {{ .Values.ingress.host }}
  to:
    kind: Service
    name: {{ .Release.Name }}-service
  port:
    targetPort: 8080
  tls:
    termination: edge
