apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  dbUsername: {{ .Values.secrets.dbUsername | b64enc }}
  dbPassword: {{ .Values.secrets.dbPassword | b64enc }}
